spring:
  activemq:
    # ActiveMq地址
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      # 是否启用连接池
      enabled: true
      # 最大的连接数
      max-connections: 50
      # 最大失效时间
      idle-timeout: 30000s
    packages:
      # activeMq信任的包
      trusted: com.cxy.entity,java.lang
      # 信任所有包
#      trust-all: true
  jms:
    # 是否启用发布订阅模式，默认为false, 即启用的是点对点模式
    pub-sub-domain: true
    # 默认目的地
    template:
      default-destination: activemq.default.destination

