spring:
  servlet:
    multipart:
      # 是否启用Spring MVC多分部上传功能
      enabled: true
      # 将文件写入磁盘的阈值，值可以使用后缀 “MB” ,"KB" 来表示兆字节或字节大小
      file-size-threshold: 0
      # 指定默认上传的文件夹
      location: e:/springboot/image
      # 限制单个文件最大大小
      max-file-size: 10MB
      # 限制所有文件最大大小
      max-request-size: 100MB
      # 是否延迟多部份文件请求的参数和文件的解析
      resolve-lazily: false