spring:
  #redis
  #配置连接池
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 192.168.10.128
    password: 123456
    timeout: 1000
  cache:
    type: redis
    cache-names: redisCache