server:
  port: 8090

spring:
  application:
    name: template_project
  profiles:
    include: datasource,redis,mybatis,log,thymeleaf,file

#logging:
#  level:
#    org.springframework.boot:
#      debug


